# Generated by Django 6.0 on 2025-12-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=5)),
                ('price_USD', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
