# Generated by Django 6.0 on 2025-12-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('wallet', models.CharField(max_length=42, unique=True)),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('raw_balance', models.IntegerField()),
                ('decimals', models.IntegerField()),
                ('adjusted_balance', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=5)),
                ('decimals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=5)),
                ('price_USD', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
