# Generated by Django 6.0 on 2025-12-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('wallet', models.CharField(max_length=42, unique=True)),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('raw_balance', models.IntegerField()),
                ('decimals', models.IntegerField()),
                ('adjusted_balance', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
