# Generated by Django 6.0 on 2025-12-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=5)),
                ('decimals', models.IntegerField()),
            ],
        ),
    ]
